version: 0.2

env:
  variables:
    AWS_REGION: "ap-south-2"
    ECR_REPO: "991524241826.dkr.ecr.ap-south-2.amazonaws.com/course-amar"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 991524241826.dkr.ecr.ap-south-2.amazonaws.com
      - export IMAGE_TAG=latest
  build:
    commands:
      - echo Building the Docker image...
      # - cd day2-microservices/course-service
      - docker build -t $ECR_REPO:$IMAGE_TAG .
      - docker tag $ECR_REPO:$IMAGE_TAG $ECR_REPO:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $ECR_REPO:$IMAGE_TAG
      - echo Writing imagedefinitions.json file...
      - printf '[{"name":"course-service","imageUri":"%s"}]' $ECR_REPO:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
